### ISSUE TITLE
Error building the 4.7.2-php7.0-fpm image.

### ISSUE THREAD

**Issue by corpulent** [docker-library/wordpress#201]
I am getting this error when building the `4.7.2-php7.0-fpm` image.  Any ideas how to fix it?

```
  Found existing installation: setuptools 5.5.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for docopt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-7JY4rH/docopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rzIlgH-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-7JY4rH/docopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rzIlgH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-7JY4rH/docopt
Storing debug log for failure in /root/.pip/pip.log
ERROR: Service 'wordpress' failed to build: The command '/bin/sh -c pip install 	awscli 	awsebcli 	colorama==0.3.7 	pprintpp 	boto' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by corpulent** [comment]
Problem is on my end, sorry.
